# <h1><center>Projet PageRank</center></h1>

## Question 1

La matrice $C_1$ associées à l'exemple 1 :
\begin{pmatrix} 
0  & 0  & 0  & 0  & 0  & 0  & 0  & 0  & 0  & 0 \\
1  & 0  & 0  & 1  & 0  & 0  & 0  & 0  & 0  & 0 \\
0  & 1  & 0  & 0  & 0  & 0  & 0  & 0  & 0  & 0 \\
0  & 1  & 1  & 0  & 0  & 0  & 0  & 0  & 0  & 0 \\
1  & 0  & 0  & 0  & 0  & 1  & 0  & 0  & 0  & 0 \\
0  & 0  & 0  & 0  & 1  & 0  & 0  & 0  & 0  & 0 \\
0  & 0  & 0  & 1  & 0  & 1  & 0  & 0  & 1  & 0 \\
0  & 0  & 0  & 0  & 0  & 0  & 1  & 0  & 1  & 0 \\
0  & 0  & 0  & 0  & 0  & 0  & 0  & 1  & 0  & 0 \\
0  & 0  & 1  & 0  & 0  & 0  & 0  & 0  & 0  & 0
\end{pmatrix}

La matrice $C_2$ associées à l'exemple 2 :
\begin{pmatrix}
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0
\end{pmatrix}

La matrice $C_3$ associées à l'exemple 3 :
\begin{pmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0
\end{pmatrix}

In [1]:
import numpy as np
from numpy import linalg as LA
import math as mt

C1 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
])

C2 = np.array([
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
])

C3 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
])

def somme_colonne (C,j) : 
    N=len(C[0,:])
    Nj=0
    for k in range (N):
        Nj += C[k][j]
    return Nj

def somme_ligne(C,i) :
    N=len(C[0,:])
    Ni=0
    for k in range (N):
        Ni += C[i][k]
    return Ni

def matrice_Q (C) :
    N=len(C[0,:])
    Q=np.zeros((N,N))
    for j in range (N):
        Nj = somme_colonne(C,j)
        for i in range (N) :
            if Nj==0 : 
                Q[i][j]=0
            else :
                Q[i][j] = C[i][j]/Nj
    return Q

def remplir_d (d,C):
    N=len(C[0,:])
    for j in range (N):
        Nj = somme_colonne(C,j)
        if Nj == 0 :
            d[j]=1

Q1=matrice_Q(C1)
Q2=matrice_Q(C2)
Q3=matrice_Q(C3)

## Question 2

La matrice $Q_1$ associées à l'exemple 1 :
\begin{pmatrix} 
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0.5 & 0 & 0 & 0.5 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0.5 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0.5 & 0.5 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
  0.5 & 0 & 0 & 0 & 0 & 0.5 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 0 &  1 & 0 & 0 & 0 & 0 & 0 \\
  0 & 0 & 0 & 0.5 & 0 & 0.5 & 0 & 0 & 0.5 & 0 \\
  0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0.5 & 0 \\
  0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
  0 & 0 & 0.5 & 0 & 0 & 0 & 0 & 0 & 0 & 0 
\end{pmatrix}

La matrice $Q_2$ associées à l'exemple 2 :
\begin{pmatrix} 
0 & 0.5 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\
 0 & 0 & 0.5 & 0.5 & 0 & 0 & 0 & 0 & 0 & 0\\
 0 & 0 & 0 & 0.5 & 0 & 0 & 0 & 0 & 0 & 0.5\\
 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0.5 & 0 & 0\\
 0 & 0 & 0.5 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\
 0 & 0.5 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\
 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.5 & 0 & 0\\
 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\
 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.5\\
 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0
\end{pmatrix}

La matrice $Q_3$ associées à l'exemple 3 :
\begin{pmatrix} 
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
 0 & 0.5& 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
 0 & 0.5& 0.5& 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 \\
 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0.5& 0 \\
 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0.5& 0 \\
 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 \\
 0 & 0 & 0.5& 0 & 0 & 0 & 0 & 0 & 0 & 0
\end{pmatrix}

## Question 3

On sait que $N_j$ = $\sum^{N}_{k = 1} C_{kj}$, donc avec $N_j$ différent de 0, on a $\frac{\sum^{N}_{k = 1} C_{kj}}{N_j} = \frac{N_j}{N_j}=1$.
Or la somme de la $j^{ieme}$ colonne de Q vaut $\sum^{N}_{k = 1} Q_{kj} = \sum^{N}_{k = 1} \frac{C_{kj}}{N_j} = \frac{\sum^{N}_{k = 1} C_{kj}}{N_j} = 1$

## Question 4

In [2]:
valeur_propre = LA.eig(Q1)[0]
print('Les valeurs propres de Q1 sont :', valeur_propre, sep='\n')

Les valeurs propres de Q1 sont :
[ 0.        +0.j         -0.5       +0.5j        -0.5       -0.5j
 -0.33117949+0.28113976j -0.33117949-0.28113976j  1.        +0.j
  0.66235898+0.j          0.70710678+0.j         -0.70710678+0.j
  0.        +0.j        ]


In [3]:
valeur_propre = LA.eig(Q2)[0]
print('Les valeurs propres de Q2 sont :', valeur_propre, sep='\n')

Les valeurs propres de Q2 sont :
[ 0.00000000e+00+0.j          8.84646177e-01+0.j
 -2.77555756e-17+0.70710678j -2.77555756e-17-0.70710678j
 -4.42323089e-01+0.2948714j  -4.42323089e-01-0.2948714j
  0.00000000e+00+0.j          0.00000000e+00+0.j
  0.00000000e+00+0.j          0.00000000e+00+0.j        ]


In [4]:
valeur_propre = LA.eig(Q3)[0]
print('Les valeurs propres de Q3 sont :', valeur_propre, sep='\n')

Les valeurs propres de Q3 sont :
[ 1. +0.j  -1. +0.j   1. +0.j  -0.5+0.5j -0.5-0.5j  0. +0.j   0. +0.j
  0. +0.j   0. +0.j   0. +0.j ]


On voit que $Q_1$ et $Q_3$ ont 1 comme valeur propre mais pas $Q_2$.

## Question 5

#### (a)

Soit X = $\begin{pmatrix} 
1 \\
1 \\
\vdots \\
1\\
1
\end{pmatrix}\in \mathbb{R}^n$ et $Q^t$ une matrice stochastique, puisque Q est stochastique, la somme de ses lignes est égal à 1. Donc $Q^t × X = X = X × 1 $ et 1 est une valeur propre de 1.

#### (b)

Soit $\lambda$ une valeur propre de $Q^t$, X= $\begin{pmatrix} 
x_1 \\
\vdots \\
x_n
\end{pmatrix}$ un vecteur propre associé et $x_i$ le plus grand coefficient de X.
En prenant la $i^{eme}$ ligne de l'égalité $Q^tX = \lambda X$, on a :
$$q_{i1}^t x_1 + ... + q_{in}^t x_n = \lambda x_i$$
En passant au module, on a :
$$|\lambda x_i| = |\lambda| |x_i| = |q_{i1}^t x_1 + ... + q_{in}^t x_n| \leq (q_{i1}^t +...+q_{in}^t) |x_i| = |x_i| $$

Donc $\lambda \leq 1$ et donc $\rho (Q^t)=1$

Soit A une matrice,
$$det(A^t - \lambda Id) = det ((A - \lambda Id)^t) = det (A -  \lambda Id)$$
Donc une matrice et sa transposée ont le même polynôme caractéristique et les mêmes valeurs propres, donc $\rho (Q^t)=\rho (Q)=1$

## Question 6

In [5]:
N= len(Q1)
e = np.ones((N,1), dtype= int)
d1 = np.zeros ((N,1), dtype= int)
remplir_d(d1,C1)
d1t=np.transpose(d1)
P1= Q1+1/N*e.dot(d1t)
print("La matrice P1 associées à l'exemple 1 :", P1,sep='\n',end='\n\n')
valeur_propre = LA.eig(P1)[0]
print('Les valeurs propres de P1 sont :', valeur_propre, sep='\n')

La matrice P1 associées à l'exemple 1 :
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.1]
 [0.5 0.  0.  0.5 0.  0.  0.  0.  0.  0.1]
 [0.  0.5 0.  0.  0.  0.  0.  0.  0.  0.1]
 [0.  0.5 0.5 0.  0.  0.  0.  0.  0.  0.1]
 [0.5 0.  0.  0.  0.  0.5 0.  0.  0.  0.1]
 [0.  0.  0.  0.  1.  0.  0.  0.  0.  0.1]
 [0.  0.  0.  0.5 0.  0.5 0.  0.  0.5 0.1]
 [0.  0.  0.  0.  0.  0.  1.  0.  0.5 0.1]
 [0.  0.  0.  0.  0.  0.  0.  1.  0.  0.1]
 [0.  0.  0.5 0.  0.  0.  0.  0.  0.  0.1]]

Les valeurs propres de P1 sont :
[ 1.00000000e+00+0.j          7.37085721e-01+0.j
  7.07106781e-01+0.j         -7.07106781e-01+0.j
 -5.00000000e-01+0.5j        -5.00000000e-01-0.5j
 -3.18542861e-01+0.26099279j -3.18542861e-01-0.26099279j
  2.29883043e-09+0.j         -2.29883051e-09+0.j        ]


In [6]:
d2 = np.zeros ((N,1), dtype= int)
remplir_d(d2,C2)
d2t=np.transpose(d2)
P2= Q2+1/N*e.dot(d2t)
print("La matrice P2 associées à l'exemple 2 :", P2,sep='\n',end='\n\n')
valeur_propre = LA.eig(P2)[0]
print('Les valeurs propres de P2 sont :', valeur_propre, sep='\n')

La matrice P2 associées à l'exemple 2 :
[[0.1 0.5 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.1 0.  0.5 0.5 0.  0.  0.  0.  0.  0. ]
 [0.1 0.  0.  0.5 0.  0.  0.  0.  0.  0.5]
 [0.1 0.  0.  0.  1.  0.  0.  0.5 0.  0. ]
 [0.1 0.  0.5 0.  0.  1.  0.  0.  0.  0. ]
 [0.1 0.5 0.  0.  0.  0.  1.  0.  0.  0. ]
 [0.1 0.  0.  0.  0.  0.  0.  0.5 0.  0. ]
 [0.1 0.  0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.1 0.  0.  0.  0.  0.  0.  0.  0.  0.5]
 [0.1 0.  0.  0.  0.  0.  0.  0.  0.  0. ]]

Les valeurs propres de P2 sont :
[ 1.        +0.j          0.36581284+0.36047335j  0.36581284-0.36047335j
  0.02596647+0.7026806j   0.02596647-0.7026806j  -0.20845507+0.45513976j
 -0.20845507-0.45513976j -0.45895162+0.2520749j  -0.45895162-0.2520749j
 -0.34874523+0.j        ]


In [7]:
d3 = np.zeros ((N,1), dtype= int)
remplir_d(d3,C3)
d3t=np.transpose(d3)
P3= Q3+1/N*e.dot(d3t)
print("La matrice P3 associées à l'exemple 3 :", P3,sep='\n',end='\n\n')
valeur_propre = LA.eig(P3)[0]
print('Les valeurs propres de P3 sont :', valeur_propre, sep='\n')

La matrice P3 associées à l'exemple 3 :
[[0.  0.  0.  0.1 0.  0.  0.  0.  0.  0.1]
 [1.  0.  0.  0.1 0.  0.  0.  0.  0.  0.1]
 [0.  0.5 0.  0.1 0.  0.  0.  0.  0.  0.1]
 [0.  0.5 0.5 0.1 0.  0.  0.  0.  0.  0.1]
 [0.  0.  0.  0.1 0.  1.  0.  0.  0.  0.1]
 [0.  0.  0.  0.1 1.  0.  0.  0.  0.  0.1]
 [0.  0.  0.  0.1 0.  0.  0.  0.  0.5 0.1]
 [0.  0.  0.  0.1 0.  0.  1.  0.  0.5 0.1]
 [0.  0.  0.  0.1 0.  0.  0.  1.  0.  0.1]
 [0.  0.  0.5 0.1 0.  0.  0.  0.  0.  0.1]]

Les valeurs propres de P3 sont :
[-5.00000000e-01+0.5j        -5.00000000e-01-0.5j
 -7.01362108e-02+0.41632364j -7.01362108e-02-0.41632364j
 -3.86155039e-01+0.j         -6.69336576e-17+0.j
  7.26427461e-01+0.j          1.00000000e+00+0.j
 -1.00000000e+00+0.j          1.00000000e+00+0.j        ]


## Question 7

La multiplication de e et la transposée de d donne une matrice de taille N × N où si la somme de la $i^{ieme}$ de $C$ est nul alors la $i^{ieme}$ colonne est composée de 1 sinon elle est composée de 0. Multiplié par $\frac{1}{N}$, les 1 deviennent des $\frac{1}{N}$ et les 0 reste des 0. $C$ et $W$ ayant les mêmes colonnes nuls, l'addition de $Q$ et $\frac{1}{N} ed^t$ comble les colonnes de 0 par $\frac{1}{N}$. 


## Question 8

Dans la question 3, on a déjà montré que la somme des colonnes non nul de Q étaient égal à 1 et si la $i^{ieme}$ colonne de Q est non nul, elle est égale à la $i^{ieme}$ colonne de P. Pour les autres colonnes, on a montré dans la question 7 qu'elles sont composées de $\frac{1}{N}$, la somme des colonnes est égale à $\sum^{N}\frac{1}{N}=1$. Donc toutes les sommes des colonnes de P sont égales à 1. Donc pour la transposé de P a la somme de ses lignes qui sont égales à 1 et est donc stochastique.
Dans la question 5, on a montré que la transposée d'une matrice stochastique a 1 comme valeur propre et que le son $\rho$ et celui de sa transposée sont égales à 1.

## Question 10

In [8]:
def alpha (P,alpha,e):
    N=len(P)
    A_alpha = np.zeros ((N,N), dtype= int)
    et=np.transpose(e)
    A_alpha = alpha * P + (1-alpha) * 1/N * e.dot(et)
    return A_alpha

def liste_module (liste) :
    nouvelle_liste=[]
    for i in range(len(liste)) :
        a=liste[i].real
        b=liste[i].imag
        nouvelle_liste.append(mt.sqrt(a**2+b**2))
    return nouvelle_liste
    
A_01_1=alpha(P1,0.1,e)
A_05_1=alpha(P1,0.5,e)
print("La matrice A_0.1 associé à l'exemple 1 :",A_01_1,sep='\n',end='\n\n')
module_valeur_propre = liste_module(LA.eig(A_01_1)[0])
print("Les modules des valeurs propres de A_01 de l'exemple 1 sont  :", sorted(module_valeur_propre,reverse=True), sep='\n',end='\n\n')

print("La matrice A_0.5 associé à l'exemple 1 :",A_05_1,sep='\n',end='\n\n')
module_valeur_propre = liste_module(LA.eig(A_05_1)[0])
print("Les modules des valeurs propres de A_05 de l'exemple 2 sont" , sorted(module_valeur_propre,reverse=True), sep='\n')

La matrice A_0.1 associé à l'exemple 1 :
[[0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.14 0.09 0.09 0.14 0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.09 0.14 0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.09 0.14 0.14 0.09 0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.14 0.09 0.09 0.09 0.09 0.14 0.09 0.09 0.09 0.1 ]
 [0.09 0.09 0.09 0.09 0.19 0.09 0.09 0.09 0.09 0.1 ]
 [0.09 0.09 0.09 0.14 0.09 0.14 0.09 0.09 0.14 0.1 ]
 [0.09 0.09 0.09 0.09 0.09 0.09 0.19 0.09 0.14 0.1 ]
 [0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.19 0.09 0.1 ]
 [0.09 0.09 0.14 0.09 0.09 0.09 0.09 0.09 0.09 0.1 ]]

Les modules des valeurs propres de A_01 de l'exemple 1 sont  :
[0.9999999999999982, 0.07370857210789918, 0.07071067811865492, 0.07071067811865465, 0.07071067811865465, 0.07071067811865463, 0.04118091646753852, 0.04118091646753852, 7.056518938127082e-10, 7.056518356426622e-10]

La matrice A_0.5 associé à l'exemple 1 :
[[0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.1 ]
 [0.3  0.05 0.05 0.3  0.05 0.05 0.05 0.05 0.05 0.1 ]
 [

In [9]:
A_01_2=alpha(P2,0.1,e)
A_05_2=alpha(P2,0.5,e)
print("La matrice A_0.1 associé à l'exemple 2 :",A_01_2,sep='\n',end='\n\n')
module_valeur_propre = liste_module(LA.eig(A_01_2)[0])
print("Les modules des valeurs propres de A_01 de l'exemple 2 sont :", sorted(module_valeur_propre,reverse=True), sep='\n',end='\n\n')
print("La matrice A_0.5 associé à l'exemple 2 :",A_05_2,sep='\n',end='\n\n')
module_valeur_propre = liste_module(LA.eig(A_05_2)[0])
print("Les modules des valeurs propres de A_05 de l'exemple 2 sont :", sorted(module_valeur_propre,reverse=True), sep='\n')

La matrice A_0.1 associé à l'exemple 2 :
[[0.1  0.14 0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.09]
 [0.1  0.09 0.14 0.14 0.09 0.09 0.09 0.09 0.09 0.09]
 [0.1  0.09 0.09 0.14 0.09 0.09 0.09 0.09 0.09 0.14]
 [0.1  0.09 0.09 0.09 0.19 0.09 0.09 0.14 0.09 0.09]
 [0.1  0.09 0.14 0.09 0.09 0.19 0.09 0.09 0.09 0.09]
 [0.1  0.14 0.09 0.09 0.09 0.09 0.19 0.09 0.09 0.09]
 [0.1  0.09 0.09 0.09 0.09 0.09 0.09 0.14 0.09 0.09]
 [0.1  0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.19 0.09]
 [0.1  0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.14]
 [0.1  0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.09 0.09]]

Les modules des valeurs propres de A_01 de l'exemple 2 sont :
[1.0, 0.07031602081229152, 0.07031602081229152, 0.05236204194883307, 0.05236204194883307, 0.05135757702229403, 0.05135757702229403, 0.05006053494806034, 0.05006053494806034, 0.034874523019469895]

La matrice A_0.5 associé à l'exemple 2 :
[[0.1  0.3  0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05]
 [0.1  0.05 0.3  0.3  0.05 0.05 0.05 0.05 0.05 0.05]
 [0.1  0.05 0.05 0.3 

In [10]:
A_01_3=alpha(P3,0.1,e)
A_05_3=alpha(P3,0.5,e)
print("La matrice A_0.1 associé à l'exemple 3 :",A_01_3,sep='\n',end='\n\n')
module_valeur_propre = liste_module(LA.eig(A_01_3)[0])
print("Les modules des valeurs propres de A_01 à l'exemple 3 sont :", sorted(module_valeur_propre,reverse=True), sep='\n',end='\n\n')
print("La matrice A_0.5 associé à l'exemple 3 :",A_05_2,sep='\n',end='\n\n')
module_valeur_propre = liste_module(LA.eig(A_05_3)[0])
print("Les modules des valeurs propres de A_05 de l'exemple 3 sont :", sorted(module_valeur_propre,reverse=True), sep='\n')

La matrice A_0.1 associé à l'exemple 3 :
[[0.09 0.09 0.09 0.1  0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.19 0.09 0.09 0.1  0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.09 0.14 0.09 0.1  0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.09 0.14 0.14 0.1  0.09 0.09 0.09 0.09 0.09 0.1 ]
 [0.09 0.09 0.09 0.1  0.09 0.19 0.09 0.09 0.09 0.1 ]
 [0.09 0.09 0.09 0.1  0.19 0.09 0.09 0.09 0.09 0.1 ]
 [0.09 0.09 0.09 0.1  0.09 0.09 0.09 0.09 0.14 0.1 ]
 [0.09 0.09 0.09 0.1  0.09 0.09 0.19 0.09 0.14 0.1 ]
 [0.09 0.09 0.09 0.1  0.09 0.09 0.09 0.19 0.09 0.1 ]
 [0.09 0.09 0.14 0.1  0.09 0.09 0.09 0.09 0.09 0.1 ]]

Les modules des valeurs propres de A_01 à l'exemple 3 sont :
[1.0000000000000002, 0.10000000000000002, 0.09999999999999998, 0.0726427461057777, 0.07071067811865471, 0.07071067811865471, 0.04221900774127305, 0.04221900774127305, 0.03861550394425758, 1.9184878209226424e-17]

La matrice A_0.5 associé à l'exemple 3 :
[[0.1  0.3  0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05]
 [0.1  0.05 0.3  0.3  0.05 0.05 0.05 0.05 0.05 0.05]
 [0.1 

## Question 11

Un élément de la matrice $A_\alpha$ à la ligne i et la colonne j est égal à $p_{ij}\alpha + \frac{(1-\alpha)}{N}$, la somme d'une colonne j est égal à $$\sum^N_{k=1} p_{kj}\alpha + \frac{(1-\alpha)}{N} = \sum^N_{k=1} p_{kj}\alpha + \sum^N_{k=1}\frac{(1-\alpha)}{N} = \alpha\sum^N_{k=1} p_{kj} + \sum^N_{k=1}\frac{(1-\alpha)}{N}  = \alpha + (1 - \alpha) = 1$$

$A_\alpha$ est strictement positif car $\alpha < 1$ implique que $\frac{(1 - \alpha)}{N}$ l'est et que donc $\alpha P+ \frac{(1 - \alpha)}{N} e e^t$ l'est aussi.

$\rho(A_\alpha)$ car on a vu dans la question 5 que le $\rho$ de la transposée d'une matrice stochastique est 1.

$A_\alpha$ a 1 comme valeur propre et qu'il existe un vecteur propre associé à 1 strictement positif comme on l'a vue dans la question 9.

## Question 12

In [11]:
def methode_puissance (A,r0) :
    r=r0
    for i in range (1,1000) :
        q=A.dot(r)
        r = q / LA.norm(q,1)
        k=0
        for j in range(len(A)):
            if LA.norm (A.dot(r)[j]-r[j])<10**(-8) :
                k+=1
                if k == len(A):
                    return r
    return None

N= len(A_01_1)

r0 = np.random.randint(5, size=(N, 1))+e
r_1=methode_puissance(A_01_1,r0)
r_2=methode_puissance(A_01_2,r0)
r_3=methode_puissance(A_01_3,r0)

print("Le vecteur approché de r tel que r=A_0.1 r pour l'exemple 1",r_1,sep='\n',end='\n\n')
print("Le vecteur approché de r tel que r=A_0.1 r pour l'exemple 2",r_2,sep='\n',end='\n\n')
print("Le vecteur approché de r tel que r=A_0.1 r pour l'exemple 3",r_3,sep='\n',end='\n\n')

Le vecteur approché de r tel que r=A_0.1 r pour l'exemple 1
[[0.09095757]
 [0.10054465]
 [0.0959848 ]
 [0.10078404]
 [0.10055611]
 [0.10101318]
 [0.10612856]
 [0.10665156]
 [0.10162273]
 [0.09575681]]

Le vecteur approché de r tel que r=A_0.1 r pour l'exemple 2
[[0.09602699]
 [0.1013344 ]
 [0.1008404 ]
 [0.10664231]
 [0.10656485]
 [0.10562557]
 [0.09598582]
 [0.1005111 ]
 [0.09550828]
 [0.09096027]]

Le vecteur approché de r tel que r=A_0.1 r pour l'exemple 3
[[0.09198739]
 [0.10118613]
 [0.09704669]
 [0.10189903]
 [0.10220821]
 [0.1022082 ]
 [0.09712092]
 [0.10683302]
 [0.10267069]
 [0.09683972]]



## Question 14


In [12]:
import time
def question_14 (Q, r0,alpha,e) :
    N=len(Q)
    s=1
    while s > 10**(-8) :
        r1 = alpha * Q.dot(r0)
        beta=1-LA.norm(r1,1)
        r2=r1+beta/N*e
        s=LA.norm(r2-r0,1)
        r0=r2
    return r0
        

In [18]:
N=1000
C=np.random.randint(2, size=(N, N))
Q=matrice_Q(C)
e = np.ones((N,1), dtype= int)
d = np.zeros ((N,1), dtype= int)
remplir_d(d,C)
dt=np.transpose(d)
P= Q+1/N*e.dot(dt)
A_01=alpha(P,0.1,e)
r0 = np.random.randint(5, size=(N, 1))+e
start = time.perf_counter()
question_14(Q,r0,0.1,e)
end = time.perf_counter()
print("Le temps d'exécution du programme de la question 14 est de ",end-start,sep=' ')
start = time.perf_counter()
methode_puissance(A_01,r0)
end = time.perf_counter()
print("Le temps d'exécution de l'algorithme des puissances est de ",end-start,sep=' ')

Le temps d'exécution du programme de la question 14 est de  0.02366970000002766
Le temps d'exécution de l'algorithme des puissances est de  6.483251999999993
